### ISSUE TITLE
unresolved reference

### ISSUE THREAD

**Issue by zhenmafan7** [dimimal/semantics_segmentation_of_urban_environments#4]
hi,thanks for your code!
In the code, there are some "unresolved reference",such as in train.py  
def select_network(args):
    if (args.model is not None) or (args.weights is not None):
        if os.path.exists(args.model) and os.path.exists(args.weights):
            return load_model(args.model, weights=args.weights)
load_model is unresolved reference 

why did this hapen?how can I fix it?

**Comment by dimimal** [comment]
I am not sure if this has to do with the script. Can you give me the command you are entering to the terminal?

**Comment by zhenmafan7** [comment]
I can't run denseExtraction.py  successfully,so I  revised it,but the .npz files I had generated are very large 
such as ：X_train_set_512_0006.npz=3.0G  Y_train_set_512_0006.npz=8.4G
Is that correct?

**Comment by zhenmafan7** [comment]
And what I enter to the terminal is 
"python train.py -n bdcnn -trp /home/wq/code/semantics_segmentation_of_urban_environments-master/Cityscapes_dataset/leftImg8bit/dense_train_set_512 -vdp /home/wq/code/semantics_segmentation_of_urban_environments-master/Cityscapes_dataset/leftImg8bit/dense_validation_set_512 -tsp /home/wq/code/semantics_segmentation_of_urban_environments-master/Cityscapes_dataset/leftImg8bit/dense_test_set_512 -bs 4 -crf -e 20"

**Comment by zhenmafan7** [comment]
Using TensorFlow backend.
---------------------------------------
 Train Set Size      ----->  6239027200  
----------------------
 Validation Set Size ----->  1048576000  
---------------------------------------
 Test Set Size       ----->  9594470400  
Traceback (most recent call last):
  File "train.py", line 151, in main
    
  File "train.py", line 52, in select_network
    return CRFRNN(args.network)
  File "/home/wq/code/semantics_segmentation_of_urban_environments-master/lib/buildModels.py", line 20, in CRFRNN
    front_model = bilinear_CNN(crf=True)
  File "/home/wq/code/semantics_segmentation_of_urban_environments-master/lib/buildModels.py", line 102, in bilinear_CNN
    model = Model(inputs=inputs, outputs=predictions)
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/keras/engine/topology.py", line 1579, in __init__
    'Keras tensors. Found: ' + str(x))
TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("div:0", shape=(?, ?, ?, 20), dtype=float32)

how can i resolve it?

**Comment by dimimal** [comment]
This is a problem in denseExtraction. Use this denseExtraction [here](https://github.com/dimimal/semantics_segmentation_of_urban_environments/blob/devel/denseExtraction.py) instead. Change the rows and columns and patchsize.

I am working onto a new data generator pipeline right now and a new approach without all this data extraction process. After you have extracted the necessary files for training, start without the crf module and then add it.

**Comment by zhenmafan7** [comment]
I used the denseExtraction.py to generate new .npz files 
but when I trying to run train.py the same error ouccured:
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    main(args)
  File "train.py", line 147, in main
    model = select_network(parameters)
  File "train.py", line 48, in select_network
    return CRFRNN(args.network)
  File "/home/wq/code/semantics_segmentation_of_urban_environments-master/lib/buildModels.py", line 20, in CRFRNN
    front_model = bilinear_CNN(crf=True)
  File "/home/wq/code/semantics_segmentation_of_urban_environments-master/lib/buildModels.py", line 102, in bilinear_CNN
    model = Model(inputs=inputs, outputs=predictions)
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/keras/engine/topology.py", line 1579, in __init__
    'Keras tensors. Found: ' + str(x))
TypeError: Output tensors to a Model must be Keras tensors. Found: Tensor("div:0", shape=(?, ?, ?, 20), dtype=float32)

I don't know what caused it,did I miss any important steps？

**Comment by dimimal** [comment]
Remove the CRF flag and tell me if the same error occurs. Ensure that you have the necessary lib versions from requirements.txt

**Comment by zhenmafan7** [comment]
I use tensorflow-gpu==1.4 instead tensorflow,I believe it doesn't matter, other libs followed requirments.txt
And I  removed CRF flag,the train.py can run epoch,but there still some errors,as followed:
Traceback (most recent call last):
  File "train.py", line 177, in <module>
    main(args)
  File "train.py", line 170, in main
    data_gen.computeTestClasses()
  File "/home/wq/code/semantics_segmentation_of_urban_environments-master/lib/dataGenerator.py", line 238, in computeTestClasses
    y = self.oneHotEncode(np.reshape(y, (y.shape[0], self.img_rows*self.img_cols)))
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/wq/.conda/envs/py27/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 368640000 into shape (200,614400)

**Comment by dimimal** [comment]
It is obvious that your data were not transformed correctly. Ensure that you're numpy files are correct. Try to load on a different script your labels, the correct shape of the file should be (n_samples, 512, 512, 20). I think the denseExtraction script might have some problems.

**Comment by zhenmafan7** [comment]
I regenerated the. npz files with denseExtraction. py, but when I ran train. py, the same error reappeared.
That's really confused me,could you please share your .npz files to me?
